### ISSUE TITLE
not an actual issue, just info you might like

### ISSUE THREAD

**Issue by Sinnisterly** [WoodgamerHD/Content-Warning-Cheat#2]
used your code as a base. Great work.

**Comment by WoodgamerHD** [comment]
with the debug console i cant see anything about the UI stuff?

**Comment by Sinnisterly** [comment]
> with the debug console i cant see anything about the UI stuff?

I myself am having a hard time enabling it, check my fork, I just pushed a bunch of stuff and the dev stuff was at the top.

**Comment by WoodgamerHD** [comment]
` if (GUILayout.Button("Console show"))
 {
     foreach (DebugUIHandler item in DebugUIHandler)
     {
         item.Show();
     }
 }
 if (GUILayout.Button("Console Hide"))
 {
     foreach (DebugUIHandler item in DebugUIHandler)
     {
         item.Hide();
     }
 }` got to show

**Comment by Sinnisterly** [comment]
> ` if (GUILayout.Button("Console show")) { foreach (DebugUIHandler item in DebugUIHandler) { item.Show(); } } if (GUILayout.Button("Console Hide")) { foreach (DebugUIHandler item in DebugUIHandler) { item.Hide(); } }` got to show

awesome, still having issues but will work on it. 
Currently trying to make TakeDamage(false); work as a constant on button press for godmode.

**Comment by WoodgamerHD** [comment]
`takeDamage = GUILayout.Toggle(takeDamage, "Take Damage");`
`    UI_Feedback.instance.TakeDamage(takeDamage);`

just used the ui feedback as a stand in

**Comment by Sinnisterly** [comment]
great great. 
also alternative to your console showing;
``if (GUILayout.Button("Open Console"))
{
    foreach (DebugUIHandler item in FindObjectsOfType<DebugUIHandler>())
    {
        item.Show();
    }
}

if (GUILayout.Button("Close Console"))
{
    foreach (DebugUIHandler item in FindObjectsOfType<DebugUIHandler>())
    {
        item.Hide();
    }
}``

**Comment by Sinnisterly** [comment]
wow githubs code blocks suck

**Comment by WoodgamerHD** [comment]
its not like discord code block its <> on the top of the text box  ``

**Comment by Sinnisterly** [comment]
> its not like discord code block its <> on the top of the text box ``

yes I clicked it and that's how it ended up putting it. oh well. you understand just as fine im sure.

**Comment by Sinnisterly** [comment]
ok nvm I'm gonna take a break from this. someone made a crazy cheeto; https://github.com/DXXNS/Content-Warning-Cheat
Only thing they're currently missing is the show console that we have.

**Comment by WoodgamerHD** [comment]
they are pasters they copy my esp when i called them out on there discord they banned me and removed the pasted esp lol

**Comment by Sinnisterly** [comment]
> they are pasters they copy my esp when i called them out on there discord they banned me and removed the pasted esp lol

oh damn, thats no good. Now I feel bad wanting to expand on theirs too.... They genuinely found stuff too which is sad, but they also copied your monsterspawn section. (I technically did too but its a direct fork + my additions 🤣 ) so I guess nvm 👍🏻
